export const nationalities = [
  "Afghan",
  "Albanian",
  "Algerian",
  "American",
  "Andorran",
  "Angolan",
  "Anguillan",
  "Citizen of Antigua and Barbuda",
  "Argentine",
  "Armenian",
  "Australian",
  "Austrian",
  "Azerbaijani",
  "Bahamian",
  "Bahraini",
  "Bangladeshi",
  "Barbadian",
  "Belarusian",
  "Belgian",
  "Belizean",
  "Beninese",
  "Bermudian",
  "Bhutanese",
  "Bolivian",
  "Citizen of Bosnia and Herzegovina",
  "Botswanan",
  "Brazilian",
  "British",
  "British Virgin Islander",
  "Bruneian",
  "Bulgarian",
  "Burkinan",
  "Burmese",
  "Burundian",
  "Cambodian",
  "Cameroonian",
  "Canadian",
  "Cape Verdean",
  "Cayman Islander",
  "Central African",
  "Chadian",
  "Chilean",
  "Chinese",
  "Colombian",
  "Comoran",
  "Congolese (Congo)",
  "Congolese (DRC)",
  "Cook Islander",
  "Costa Rican",
  "Croatian",
  "Cuban",
  "Cymraes",
  "Cymro",
  "Cypriot",
  "Czech",
  "Danish",
  "Djiboutian",
  "Dominican",
  "Citizen of the Dominican Republic",
  "Dutch",
  "East Timorese",
  "Ecuadorean",
  "Egyptian",
  "Emirati",
  "English",
  "Equatorial Guinean",
  "Eritrean",
  "Estonian",
  "Ethiopian",
  "Faroese",
  "Fijian",
  "Filipino",
  "Finnish",
  "French",
  "Gabonese",
  "Gambian",
  "Georgian",
  "German",
  "Ghanaian",
  "Gibraltarian",
  "Greek",
  "Greenlandic",
  "Grenadian",
  "Guamanian",
  "Guatemalan",
  "Citizen of Guinea-Bissau",
  "Guinean",
  "Guyanese",
  "Haitian",
  "Honduran",
  "Hong Konger",
  "Hungarian",
  "Icelandic",
  "Indian",
  "Indonesian",
  "Iranian",
  "Iraqi",
  "Irish",
  "Israeli",
  "Italian",
  "Ivorian",
  "Jamaican",
  "Japanese",
  "Jordanian",
  "Kazakh",
  "Kenyan",
  "Kittitian",
  "Citizen of Kiribati",
  "Kosovan",
  "Kuwaiti",
  "Kyrgyz",
  "Lao",
  "Latvian",
  "Lebanese",
  "Liberian",
  "Libyan",
  "Liechtenstein citizen",
  "Lithuanian",
  "Luxembourger",
  "Macanese",
  "Macedonian",
  "Malagasy",
  "Malawian",
  "Malaysian",
  "Maldivian",
  "Malian",
  "Maltese",
  "Marshallese",
  "Martiniquais",
  "Mauritanian",
  "Mauritian",
  "Mexican",
  "Micronesian",
  "Moldovan",
  "Monegasque",
  "Mongolian",
  "Montenegrin",
  "Montserratian",
  "Moroccan",
  "Mosotho",
  "Mozambican",
  "Namibian",
  "Nauruan",
  "Nepalese",
  "New Zealander",
  "Nicaraguan",
  "Nigerian",
  "Nigerien",
  "Niuean",
  "North Korean",
  "Northern Irish",
  "Norwegian",
  "Omani",
  "Pakistani",
  "Palauan",
  "Palestinian",
  "Panamanian",
  "Papua New Guinean",
  "Paraguayan",
  "Peruvian",
  "Pitcairn Islander",
  "Polish",
  "Portuguese",
  "Prydeinig",
  "Puerto Rican",
  "Qatari",
  "Romanian",
  "Russian",
  "Rwandan",
  "Salvadorean",
  "Sammarinese",
  "Samoan",
  "Sao Tomean",
  "Saudi Arabian",
  "Scottish",
  "Senegalese",
  "Serbian",
  "Citizen of Seychelles",
  "Sierra Leonean",
  "Singaporean",
  "Slovak",
  "Slovenian",
  "Solomon Islander",
  "Somali",
  "South African",
  "South Korean",
  "South Sudanese",
  "Spanish",
  "Sri Lankan",
  "St Helenian",
  "St Lucian",
  "Stateless",
  "Sudanese",
  "Surinamese",
  "Swazi",
  "Swedish",
  "Swiss",
  "Syrian",
  "Taiwanese",
  "Tajik",
  "Tanzanian",
  "Thai",
  "Togolese",
  "Tongan",
  "Trinidadian",
  "Tristanian",
  "Tunisian",
  "Turkish",
  "Turkmen",
  "Turks and Caicos Islander",
  "Tuvaluan",
  "Ugandan",
  "Ukrainian",
  "Uruguayan",
  "Uzbek",
  "Vatican citizen",
  "Citizen of Vanuatu",
  "Venezuelan",
  "Vietnamese",
  "Vincentian",
  "Wallisian",
  "Welsh",
  "Yemeni",
  "Zambian",
  "Zimbabwean",
];

export const visaCategories = [
  "Citizen",
  "Student",
  "Concurrent",
  "Work Visa",
  "Permanent Resident(PR)",
  "Visitor",
  "Business Visa",
  "Green Card",
];

export const allCastes = [
  "Patel-Desai",
  "Patel-Kadva",
  "Patel-Leva",
  "Patel",
  "Brahmin-Audichya",
  "Brahmin",
  "Jain-Digambar",
  "Jain-Swetamber",
  "Jain-Vanta",
  "Vaishnav-Vania",
];

export const requiredFields = [
  "birthCity",
  "birthState",
  "height",
  "weight",
  "rashi",
  "religion",
  "nationality",
  "street1",
  "pincode",
  "city",
  "state",
  "legalStatus",
  "interCommunity",
];
export const doshOptions = [
  "No Dosh",
  "Manglik",
  "Ashnik Manglik",
  "Sarpa Dosh",
  "Kala Sarpa Dosh",
  "Rahu Dosh",
  "Ketu Dosh",
  "Kalathra Dosh",
];

export const fieldLabels = {
  birthCity: "Birth City",
  birthState: "Birth State",
  height: "Height",
  weight: "Weight",
  rashi: "Rashi",
  religion: "Religion",
  nationality: "Nationality",
  street1: "Street Address 1",
  pincode: "Pincode",
  city: "City",
  state: "State",
  legalStatus: "Legal Status",
  interCommunity: "Marry to other community",
};

export const weightOptions = [
  "40 kg / 88 lbs",
  "41 kg / 90 lbs",
  "42 kg / 93 lbs",
  "43 kg / 95 lbs",
  "44 kg / 97 lbs",
  "45 kg / 99 lbs",
  "46 kg / 101 lbs",
  "47 kg / 104 lbs",
  "48 kg / 106 lbs",
  "49 kg / 108 lbs",
  "50 kg / 110 lbs",
  "51 kg / 112 lbs",
  "52 kg / 115 lbs",
  "53 kg / 117 lbs",
  "54 kg / 119 lbs",
  "55 kg / 121 lbs",
  "56 kg / 123 lbs",
  "57 kg / 126 lbs",
  "58 kg / 128 lbs",
  "59 kg / 130 lbs",
  "60 kg / 132 lbs",
  "61 kg / 134 lbs",
  "62 kg / 137 lbs",
  "63 kg / 139 lbs",
  "64 kg / 141 lbs",
  "65 kg / 143 lbs",
  "66 kg / 146 lbs",
  "67 kg / 148 lbs",
  "68 kg / 150 lbs",
  "69 kg / 152 lbs",
  "70 kg / 154 lbs",
  "71 kg / 157 lbs",
  "72 kg / 159 lbs",
  "73 kg / 161 lbs",
  "74 kg / 163 lbs",
  "75 kg / 165 lbs",
  "76 kg / 168 lbs",
  "77 kg / 170 lbs",
  "78 kg / 172 lbs",
  "79 kg / 174 lbs",
  "80 kg / 176 lbs",
  "81 kg / 179 lbs",
  "82 kg / 181 lbs",
  "83 kg / 183 lbs",
  "84 kg / 185 lbs",
  "85 kg / 187 lbs",
  "86 kg / 190 lbs",
  "87 kg / 192 lbs",
  "88 kg / 194 lbs",
  "89 kg / 196 lbs",
  "90 kg / 198 lbs",
  "91 kg / 201 lbs",
  "92 kg / 203 lbs",
  "93 kg / 205 lbs",
  "94 kg / 207 lbs",
  "95 kg / 209 lbs",
  "96 kg / 212 lbs",
  "97 kg / 214 lbs",
  "98 kg / 216 lbs",
  "99 kg / 218 lbs",
  "100 kg / 220 lbs",
];
export const heightOptions = [
  "4'0\" / 122 cm",
  "4'1\" / 124 cm",
  "4'2\" / 127 cm",
  "4'3\" / 130 cm",
  "4'4\" / 132 cm",
  "4'5\" / 135 cm",
  "4'6\" / 137 cm",
  "4'7\" / 140 cm",
  "4'8\" / 142 cm",
  "4'9\" / 145 cm",
  "4'10\" / 147 cm",
  "4'11\" / 150 cm",
  "5'0\" / 152 cm",
  "5'1\" / 155 cm",
  "5'2\" / 157 cm",
  "5'3\" / 160 cm",
  "5'4\" / 163 cm",
  "5'5\" / 165 cm",
  "5'6\" / 168 cm",
  "5'7\" / 170 cm",
  "5'8\" / 173 cm",
  "5'9\" / 175 cm",
  "5'10\" / 178 cm",
  "5'11\" / 180 cm",
  "6'0\" / 183 cm",
  "6'1\" / 185 cm",
  "6'2\" / 188 cm",
  "6'3\" / 191 cm",
  "6'4\" / 193 cm",
];
